name: SearchObjects build test

on:
  push:
    branches-ignore: 
      - main
    paths:
      - 'Frends.LDAP.SearchObjects/**'
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/linux_build_test.yml@main
    with:
      workdir: Frends.LDAP.SearchObjects
      prebuild_command: |
        docker run -d -i --rm -p 10389:10389 dwimberger/ldap-ad-it
        docker run -d -i --rm -p 20389:389 osixia/openldap:1.5.0 \
          --env LDAP_ORGANISATION="Test Org" \
          --env LDAP_DOMAIN="example.org" \
          --env LDAP_ADMIN_PASSWORD="admin"

        for i in {1..30}; do
            nc -z 127.0.0.1 20389 && echo "LDAP ready" && break
            echo "Waiting for LDAP..." && sleep 1
        done
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      test_feed_api_key: ${{ secrets.TASKS_TEST_FEED_API_KEY }}